"""Signal 1: LLM-based holistic classification via Groq.

Asks the model to judge whether text reads as human- or AI-written and
return a structured AI-likelihood score plus a short rationale. See
planning.md section 2 for what this captures and its blind spots.
"""

import json
import os
import re

from groq import Groq

from config import GROQ_MODEL

_SYSTEM_PROMPT = (
    "You are an assistant that helps a creative-writing platform assess "
    "whether submitted text was likely written by a human or generated by "
    "an AI language model. Judge based on semantic coherence, natural "
    "imperfection, idiomatic phrasing, and whether the writing has the "
    "uneven, idiosyncratic quality of human thought versus the smoothed, "
    "generically fluent quality common in AI-generated prose.\n\n"
    "Respond with ONLY a JSON object, no other text, in this exact shape:\n"
    '{"ai_likelihood": <float 0.0-1.0, where 1.0 = certainly AI-generated '
    'and 0.0 = certainly human-written>, "rationale": "<one or two '
    'sentence explanation>"}'
)

_JSON_RE = re.compile(r"\{.*\}", re.DOTALL)

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set")
        _client = Groq(api_key=api_key)
    return _client


def analyze(text):
    """Return (ai_likelihood_score, feature_breakdown) for the given text.

    Falls back to a neutral, clearly-flagged result if the Groq API is
    unavailable, rather than failing the whole submission.
    """
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        match = _JSON_RE.search(raw)
        payload = json.loads(match.group(0) if match else raw)
        score = float(payload["ai_likelihood"])
        score = max(0.0, min(1.0, score))
        return score, {
            "model": GROQ_MODEL,
            "rationale": payload.get("rationale", ""),
            "available": True,
        }
    except Exception as exc:  # noqa: BLE001 - any failure degrades gracefully
        return 0.5, {
            "model": GROQ_MODEL,
            "rationale": f"LLM signal unavailable, defaulted to neutral: {exc}",
            "available": False,
        }
